version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "7123"
    network_mode: "host"
  goose:
    build:
      context: .
      dockerfile: migration.Dockerfile
    network_mode: "host"
    depends_on:
      - "postgres"
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "sh",  "/app/goosemigration.sh"]
    volumes:
      - .:/app_directory
  api_server:
    build:
      context: .
      dockerfile: api.Dockerfile
    network_mode: "host"
    depends_on:
      - "postgres"
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "/app/cmd/main",""]